name: CI/CD

on:
  push:
    branches:
      - '*develop*'
      - '*master*'
  pull_request:
    branches:
      - '*develop*'
      - '*master*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install cmake
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install cmake --version 3.21.2
          else
            brew install cmake
          fi

      - name: Build
        run: cmake . && cmake --build .

      - name: Test
        run: ctest

      - name: Deploy Results
        run: |
          echo 'Deploying build results...'
          # Insert your deployment commands here.
